### ISSUE TITLE
Update pushed did not fix 4.0.72

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#10]
Previous update didn't show links after source scan just  .. Now source ends and no spin or dialog can you put up 4.0.70 until solution found as it worked perfectly and was best on kodi (perhaps rename as 4073)

**Comment by Tempest0580** [comment]
Yes I'll push the 4.0.70 until I can figure out the issue.

**Comment by Tempest0580** [comment]
Pushed a update back to 4.0.70 code, Give it a few minutes and update it.
