### ISSUE TITLE
preemptive termination

### ISSUE THREAD

**Issue by thefrench1** [Tempest0580/tempest#11]
hi  love this addon been using it for a while now, im just wondering it it was possible to have a preemptive termination added to  it like some other addons, the reason i like this one so much is the 24hr delay before import, which is a great feature and adding the preemptive term would take this addon to the next level as theres not many addons out there at the moment that do both.

kind regards

**Comment by Tempest0580** [comment]
I'll look into adding it back. I had it a while back but I felt it didnt work correctly.  But yes I'll look into it. About to do a bunch of updates and adding new scrapers as well. Thanks

**Comment by Tempest0580** [comment]
Did a quick update for the week, Added  Pre-Emptive Termination. Please test it and let me know how it is working. I wont be able to do any more work on Tempest until next week. Thanks

**Comment by thefrench1** [comment]
Hi thanks for a the quick update, i have just had a quick look and  the pre-emptie termination  appears to be working for me i have it set to max 1080p and terminate at 10 and it does just that. amazing and quick quick.

**Comment by Tempest0580** [comment]
Your welcome. I'm glad to hear its working for you.
