### ISSUE TITLE
swatchseries appears to be down

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/tempest#14]
Hey Tempest,
At least on my setup, swatchseries is down. It doesn't show on any series, that I've tried, after a scan. It's one of the best sources, as you know.

Have a good one. :).

Later...

**Comment by Tempest0580** [comment]
Ok I'll take a look. Thanks.

**Comment by Tempest0580** [comment]
Swatchseries is working again. The search function was broken on the site but looks like they fixed it.

**Comment by bjgood** [comment]
Thanks for the heads up, Tempest. It is working now.

Later...
