### ISSUE TITLE
TV shows not pulling any links 

### ISSUE THREAD

**Issue by DoBucki** [Tempest0580/tempest#15]
And the shows have <|[CDATA[SHOW]] > on all

**Comment by Tempest0580** [comment]
It looks like TVBD is having issues with the new website and its cause kodi addons problems pulling artwork. They are working on the problem.

**Comment by DoBucki** [comment]
Movies are working and TV shows in history folder.  All other TV shows not even an option for play with.

**Comment by Tempest0580** [comment]
According to Tvdb they have found the problem and working on pushing a fix for it.

**Comment by Tempest0580** [comment]
Pushed a fix for Tvshows, The artwork is still not downloading right because of Tvdb server issue but you can now watch show.
