### ISSUE TITLE
Trakt issue

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#16]
When I enter my tvshows/collection all my shows are listed but when I click on any the item does not enter the seasons list this is also true if I try any TV shows outside trakt. Is this a bug as trakt appears to be up and running?

**Comment by Tempest0580** [comment]
I believe it has to do with the issue tvdb is having. Hopefully they will have everything fixed soon. I'm working on adding a fix for any future issue but it will take a while and tvdb will probably be fixed before I can push any kind of fix

**Comment by Pawman63** [comment]
Thank you for the time to respond. I have seen accounts of the issue now hopefully all will be okay soon.

**Comment by Tempest0580** [comment]
Pushed a fix for Tvshows, The artwork is still not downloading right because of Tvdb server issue but you can now watch show.
