### ISSUE TITLE
No ticks after watching a TV series

### ISSUE THREAD

**Issue by jazzguyuk1** [Tempest0580/tempest#17]
Hi..after watching a TV series it's not leaving a tic that the episode had been watched. I'm using Leila 18.5 and eps that had problem was latest eps of curse of oak island ..watching a film that's ok that leaves a tic..worked ok before all the problems when they moved to v3..thanks for a brilliant add on and all the updates you do..brilliant work

**Comment by Tempest0580** [comment]
I'll look into it as soon as I can.
Thanks

**Comment by bjgood** [comment]
Same problem. Father Brown season 1 is one you can check with.

**Comment by bjgood** [comment]
It could be due to this tvdb fiasco. A lot of things are not like they were before this blew up.

**Comment by Tempest0580** [comment]
Ya I noticed some minor issues with the artwork. Try clearing the meta and the cache. I'm working on the code to try and improve tvdb and trakt.

**Comment by bjgood** [comment]
Does clearing the meta and cache fix the problem?

**Comment by Tempest0580** [comment]
It should help with some issues, i always clear them both with every update myself.
For the most part Trakt is checking all my shows. still working on the code to improve everything all around.

**Comment by Tempest0580** [comment]
Just Pushed a update that should speed everything up a little bit. clear Meta and cache and test it and let me know if it helps.
Thanks

**Comment by jazzguyuk1** [comment]
No still doesn't work..before you could tick a whole season watched ie
MasterChef UK.. now if you go into that series only the first eps is ticked
all the rest no ticks as I watched them before on bbc as I had a TV licence
now I've cancelled my TV licence as all ones I use to watch I've found in
tempest which I watch daily but trouble seems since all the trouble with tv
series moving to v3

**Comment by Tempest0580** [comment]
Ok I'm still working on the code. Hopefully I'll have it done tonight and get it pushed.

**Comment by jazzguyuk1** [comment]
Thanks

**Comment by jazzguyuk1** [comment]
hi.. ive seen you've closed it...is the ticks back in tv series ??…  thanks
for all the recent updates film links are spot on.. thanks again for all
your hard work...nigel
