### ISSUE TITLE
no sources for Empire Tv Show

### ISSUE THREAD

**Issue by doraviar1** [Tempest0580/tempest#18]
when i search in tv shows he found empire but when i clicked on empire he showed nothing so if you can fix this i will be happy thank you for reading this good luck fixing this.
btw im using kodi version 17.6 krypton

**Comment by Tempest0580** [comment]
It may have something to do with tvdb api. They changed things last night. They did it to try and fix things. I'm hoping to try and push a fix tonight so it may fix it.

**Comment by Tempest0580** [comment]
Just Pushed a update that should fix the issue. Let me know. Thanks

**Comment by doraviar1** [comment]
thank you tempest you are the best im gonna check right now

**Comment by Tempest0580** [comment]
I'm going to assume this has been resolved and going to close this.
