### ISSUE TITLE
I can’t watch any tv shows

### ISSUE THREAD

**Issue by ThatTwoGuy** [Tempest0580/tempest#19]
Movies are fine but any tv show folder doesn’t open

**Comment by Tempest0580** [comment]
I am aware of it. Tvdb has changed the api again to try and fix things. I should be pushing a fix for it later today.

**Comment by ThatTwoGuy** [comment]
> I am aware of it. Tvdb has changed the api again to try and fix things. I should be pushing a fix for it later today.

Aight thx
