### ISSUE TITLE
ScraperTalk

### ISSUE THREAD

**Issue by jewbmx** [Tempest0580/tempest#2]
Came across a spare tire for ya. 123movies4u or whatever the exact name might be has another url you can add to it as a backup  123movies.live

**Comment by jewbmx** [comment]
Thought id be helpful and do some testing for ya and found a few little things that are screwed up for 18.

In your settings

`<setting type="lsep" label="32359" />`

My fix for it is

`<setting type="text" label="32359" enable="false" />`

Probably other ways but this is easy and i like it with my skin colors lol.

This might fix your fanart label issue too.

If ya wanna add the bookmarks auto option i think its just the bookmarks class in player.py def get and reset.

Gotta update certificates still in movies and shows indexers.

Might wanna check out the people search option for shows, tried a couple names in each search spots and never got a result.

(Thats all i spot right now.)

**Comment by Tempest0580** [comment]
Just seen this. Thanks I'll look into them.
