### ISSUE TITLE
Collection no longer allows opening of series

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#20]
Is tvdb down again as the same thing has started to occur again where it is impossible to open series.

**Comment by Tempest0580** [comment]
I am aware of the issue and will be pushing a update in a hour or so. Thanks

**Comment by Tempest0580** [comment]
Just Pushed a update that should fix the issue.

**Comment by Pawman63** [comment]
Thanks as always.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tempest0580** [comment]
Your welcome.
