### ISSUE TITLE
Having TVDB issues again as before.

### ISSUE THREAD

**Issue by durangorob** [Tempest0580/tempest#21]
Having TVDB issues again as before...unable to browse tv series or access programs from trakt collection. Please help and advise.

**Comment by Tempest0580** [comment]
Check for a update. I pushed a update to fix it for the most part.
They changed some more stuff with the api. Waiting for them to finish to try and fix it fully.

**Comment by Tempest0580** [comment]
Clear metadata and cache too.

**Comment by durangorob** [comment]
Thanks for pushing the update.  Seems to working again. 

Sent from AT&T Yahoo Mail on Android 
 
  On Mon, Nov 25, 2019 at 9:34 PM, Tempest<notifications@github.com> wrote:   
Clear metadata and cache too.

**Comment by Tempest0580** [comment]
Your Welcome
