### ISSUE TITLE
Progress not working for Trakt

### ISSUE THREAD

**Issue by Techmuse** [Tempest0580/tempest#22]
When selecting progress using Trakt nothing is returned.  Collections and watchlist appear to work fine.  Progress was working at 5.0.2 for sure.  Not sure I tried it on 5.0.3 so not sure if it was working then. Definitely not working on 5.0.4

**Comment by Tempest0580** [comment]
I'll look into it.  Thanks

**Comment by Tempest0580** [comment]
I pushed a update. I tweaked the Tvdb artwork. on my end it seems to have fixed the progress through Trakt. Let me know if it fixed it for you as well.
Thanks

**Comment by Techmuse** [comment]
Both of my kodi boxes show the last update as done 11/25 ver 5.0.4 still. Tried to force an update but still only shows 5.0.4 available.  I’ll try again tonight in 12 hours or so and see if the push has gone through

**Comment by Techmuse** [comment]
Box updated to kodi 18.5 and tempest 5.0.5 today.  Progress now seems to be working again. Thx

**Comment by Tempest0580** [comment]
Your welcome and I'm glad to hear it.
Thanks
