### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#23]
No issue with your great work on tempest but wondered if you know from your inside view what is happening with rlsbb as it seems to have disappeared from sources and it's own addon.

**Comment by Tempest0580** [comment]
I'll try to look into the scraper tonight.

**Comment by marson53** [comment]
Looks like its a Cloudflare  issue,  kodi cfscrape script needs updating

**Comment by Tempest0580** [comment]
I agree it's a Cloudflare issue. Its affecting a few scrapers. I'm looking into seeing if I can fix it or find a updated version of cfscrape.

**Comment by Tempest0580** [comment]
I pushed a update that should fix this.
Thanks
