### ISSUE TITLE
swatchseries

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/tempest#24]
Hey Tempest,
Is swatchseries working for you? I don't seem to be getting any results from it at all.

Thanks for all your hard work, and this update.

Have a good one. :).

**Comment by Tempest0580** [comment]
I'll check it this afternoon.

**Comment by bjgood** [comment]
I've observed that the new cfscrape for 5.0.12 is quite slow compared to 5.0.11. I assume that's what is slowing a scan for links down.

**Comment by Tempest0580** [comment]
I think it's in the new cfscrape.  If so I'll push a temporary fix for it tonight.

**Comment by Tempest0580** [comment]
Looks like they chanced some stuff on the site. Soon as I get a chance I'll look more into this.

**Comment by shellc0de27** [comment]
@Tempest0580 Any progress on this? If you are stuck, what part?

**Comment by Tempest0580** [comment]
Time really. Between work and life. Plus I'm re coding for the 1 click movies and adding shows to tempest and temptv I just haven't had alot of time to get back to it. I looked after it broke and I know the site changed just haven't got a chance to see if I can update the scraper yet.

**Comment by shellc0de27** [comment]
I hear you, been the same here too especially with the holidays and what not.
Well try these few things to get the scraper running again....

- The first request in the tvshow function needs to be switched to a "get".
- Dont think u need the quote plus anymore for that request.
- Once you can bring the link down to sources, have a look at the page html.
- You will see that we can pull those links different using a simple regex
- and you can remove base64 shit.
Any questions let me know

**Comment by shellc0de27** [comment]
Here is a time saver. Had to zip it i guess
[swatchseries.zip](https://github.com/Tempest0580/tempest/files/4022568/swatchseries.zip)

**Comment by Tempest0580** [comment]
Thanks that will help. I'll get it pushed soon as I get a chance.

**Comment by shellc0de27** [comment]
Yeah no problem man :)

**Comment by bjgood** [comment]
Wish I checked here 2 days ago instead of now.

Thanks, shellc0de27, for the swatchseries fix. It works. Wish you  had a public repo so one could visit you.

**Comment by Tempest0580** [comment]
Pushed a update to fix this. Thanks again shellc0de27

**Comment by jewbmx** [comment]
You have been sitting on a fixed version of this scraper ever since i emailed you that one module Tempest lol

**Comment by Tempest0580** [comment]
Doesnt surprise me lol. Just had alot going on.

**Comment by shellc0de27** [comment]
@jewbmx  lmao nice. Did you basically take the same approach?

**Comment by jewbmx** [comment]
Havent looked to be honest but the regex i used for that site is ("'Delete link (.+?)'")  Theres a few more like it i had to update to use a variation of the same sorta grab lol
