### ISSUE TITLE
Rlsbb fails in new update

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#25]
Thanks for all your great work but rlsbb results are not coming through on latest update.

**Comment by Tempest0580** [comment]
I'll double check it tonight.  I thought it was working fine before the update.

**Comment by Tempest0580** [comment]
I'll push a temporary fix for this tonight.
Until I can get the coding right for the last update.

**Comment by Pawman63** [comment]
Hi sorry if there has been any stuff that got in the way just looking for an update on the fix/update you mentioned.

**Comment by Tempest0580** [comment]
My computer has been acting up. I'm going to try to push the update later today.

**Comment by Tempest0580** [comment]
Pushed a update that should fix this. The test I ran fixed it.
