### ISSUE TITLE
1337x and limetorrents

### ISSUE THREAD

**Issue by marson53** [Tempest0580/tempest#26]
Hi, Tempest , with being in the UK i have to use a Proxy for some torrents to work
I have just lost 1337x torrent today and limetorrents  4weeks ago 
i usually just find a new proxy, and change the torrent py  to get hem to work again
But for some reason i cant get 1337x or limetorrents to work now with the new proxy i have found 
these work in my browser but not in tempest , something must have changed not sure what 
If its too much trouble to help i understand

these work in my browser, but not in tempest when i change the torrent py address
new 1337x proxy  https://1337x.gd
new limetorrents proxy  https://www.limetor.pro

class source:
    def __init__(self):
        self.priority = 1
        self.language = ['en']
        self.domains = ['1337x.gd', 'www.1337x.wtf', '1337x.app']
        self.base_link = 'https://1337x.gd/'
        self.tvsearch = 'https://1337x.gd/sort-category-search/{0}/TV/seeders/desc/{1}/'
        self.moviesearch = 'https://1337x.gd/sort-category-search/{0}/Movies/size/desc/{1}/'
Thanks

**Comment by Tempest0580** [comment]
Looks like I should be able to change limetorrents without any issues. Not sure about 1337 yet. But I'm looking into this.
