### ISSUE TITLE
Trakt progress not working correctly again

### ISSUE THREAD

**Issue by Techmuse** [Tempest0580/tempest#27]
Actually 2 issues here.  

1) progress is pulling watched episodes as well as those that are yet to be watched.  It should only pull non watched episodes. 
2) sort order is weird, possibly due to the issue in 1.  Episodes are being sorted by episode number regardless of season. For example 1x01, 2x01, 3x01, 1x02, 2x02, etc. Should sort by season, then episode. Sort as is would be fine only if a single season existed in list.

**Comment by Tempest0580** [comment]
I put this on the list to look into.

**Comment by host505** [comment]
For 2, see here https://github.com/Tempest0580/tempest/issues/28#issuecomment-569943874
Unfortunately this doesn't solve the trakt progress issue, tvdb has to restore their api as before the changes for it to be fixed, as it returns wrong episodes/seasons orders (hence the forced sorting method for listing)

**Comment by Tempest0580** [comment]
Pushed a Update that should fix this.

**Comment by Techmuse** [comment]
Thanks.  Looks like it’s working now. Checked my settings re flattened seasons.  As I thought flatten seasons if off.  

Thanks again for all your effort.

**Comment by Tempest0580** [comment]
Your welcome.  Glad it worked out.
