### ISSUE TITLE
TV episodes not sequenced

### ISSUE THREAD

**Issue by sidpapa984** [Tempest0580/tempest#28]
Hi,
Thanks for your add-on.
Since last 3 updates, series episodes are not showing in sequence. You get a listing showing seasons in sequence, each with only episode 1, then the next group only shows episode 2, and so on.
I am using kodi 18.5 and confluence skin.

**Comment by Tempest0580** [comment]
Have to tried to clean metadata and cache?  I haven't noticed any issue with it.

**Comment by host505** [comment]
I guess op uses 'flattened seasons' view.
@Tempest0580 change line 500 of your episodes.py from
`self.list = sorted(self.list, key=lambda k: int(k['episode']))`
to
`self.list = sorted(self.list, key=lambda k: (int(k['season']), int(k['episode'])))`

**Comment by Tempest0580** [comment]
Thanks for catching that. I'll try to push a update tonight on it.

**Comment by Tempest0580** [comment]
I forgot all about 'flattened seasons' lol
I never use it myself

**Comment by host505** [comment]
Yeah me too, walking dead or supernatural would take forever to load lol
For the record, don't know if you made this sorting or seen it somewhere, I came up with this some 2 weeks ago, and 3 days later realised this flattened seasons bug which I fixed then.
I guess it got rolled out before the fix lol

**Comment by Tempest0580** [comment]
Honestly I think someone emailed me about it. Lol
But I need to start visiting your github more often. Lol

**Comment by host505** [comment]
Too bad they ain't giving you the source.
Take what you want with a grain of salt, I do whatever dum thing come into my brain - my readme is for real lol

**Comment by Tempest0580** [comment]
Oh I get it. Now I did test it just forgot about the flattened seasons lol. I have borrowed code from your github but ofcourse when i do shit like that i try to always give credit. 

I would have probably figured out that it needed to be modified for the

**Comment by host505** [comment]
Nah not saying that for credit, really don't care, I just chimmed in because I knew the bug first hand.
You know there are people that have literally cloned my add-on, along with my API keys, and just renamed it/changed artwork and put it into builds and shit like this. That's fucked.
I'm not looking for credit for such small things from honest devs.

**Comment by Tempest0580** [comment]
Oh I know. I was just putting that out there lol. I just dont like using someone else's code or even scrapers without giving credit. 
Hell most of the most common scrapers in all these addons were either mine or the ones I fixed after being broke for while. Yet not many people give me credit. They just take lol.

And I wouldn't put it past people cloning your addon like that. My has been too. And I know Jewbmx addons has been. People suck lol.

**Comment by Tempest0580** [comment]
Pushed a Update that should fix this.
