### ISSUE TITLE
IMDB lists not working

### ISSUE THREAD

**Issue by Ggreendd** [Tempest0580/tempest#29]
The TV list links the series list but does not proceed to link the season and episodes.

**Comment by Tempest0580** [comment]
I dont use them myself but thanks for letting me know. I'll look into it.

**Comment by Ggreendd** [comment]
Thanks. Tempest is my first add on of choice- great job!

David

Sent from my iPhone

“Those who can make you believe absurdities, can make you commit atrocities.” - Voltaire

On Jan 24, 2020, at 7:39 PM, Tempest <notifications@github.com> wrote:

I dont use them myself but thanks for letting me know. I'll look into it.

**Comment by Tempest0580** [comment]
So with the testing i have done i cant seem to find and issues with the IMDB list. Can you walk me thru you the issue you are having? 
Thanks

**Comment by Ggreendd** [comment]
I just tested Tempest and it is working now. When I sent you the message, I was able to click on My TV Shows then TV Lists but clicking on a show did not display the seasons. Now it works!?

Great addon

Thanks for the follow up.

David

Sent from my iPhone

“Those who can make you believe absurdities, can make you commit atrocities.” - Voltaire

On Feb 1, 2020, at 1:50 PM, Tempest <notifications@github.com> wrote:

So with the testing i have done i cant seem to find and issues with the IMDB list. Can you walk me thru you the issue you are having?
Thanks

**Comment by Tempest0580** [comment]
Its possible it may have also been a issue with tvdb. But I'm glad it's all working now.
