### ISSUE TITLE
UsaTv Go 

### ISSUE THREAD

**Issue by ts2art** [Tempest0580/tempest#35]
Last couple days UsaTv Go has been working. Usually i will see playlist.m3u8 at the top of the screen but not anymore. Any help would greatly be appreciated. Thank you

**Comment by Tempest0580** [comment]
Something is going on with the site right now. Not sure what's going on with it yet.

**Comment by ts2art** [comment]
Thanks for the quick response!! We really enjoy Tempest and TempTv.

**Comment by Tempest0580** [comment]
Thanks, I'm glad to hear it.

**Comment by Tempest0580** [comment]
Pushed a fix for UstvGo, Not sure how long it will last though.
Thanks

**Comment by ts2art** [comment]
It was working last night! Thanks again

**Comment by ts2art** [comment]
I have a question... maybe you can help me with. I installed Kodi 18.6 and
tempest, temptv and the Crew. It worked fine a couple days ago.... now
regardless of which add on used, there are no movies or tv shows shown. The
page is blank and says at the top 0/0.
Any help would greatly be appreciated! Thank you in advance!!

**Comment by Tempest0580** [comment]
> I have a question... maybe you can help me with. I installed Kodi 18.6 and tempest, temptv and the Crew. It worked fine a couple days ago.... now regardless of which add on used, there are no movies or tv shows shown. The page is blank and says at the top 0/0. Any help would greatly be appreciated! Thank you in advance!!

Did you figure this out? Without a log I cant really do much. Everything is working fine on my end.
Thanks

**Comment by ts2art** [comment]
I suspect it has to do with a Kodi setting. Firestick in the room works
fine.... The one in the living room blank!! I guess just uninstalling kodi
and reinstalling is the answer. Thank you

**Comment by Tempest0580** [comment]
Sounds like a good plan. Lol
Your welcome.
