### ISSUE TITLE
Not opening series

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#36]
Strange one this so could be outside issue rather than tempest a number of series in my collection fail to open greys anatomy is one it want open yet just below Grimm no issue all seasons appear any idea what's causing the issue ?

**Comment by Tempest0580** [comment]
Not really sure. I haven't noticed any issues on mine. But I'll take a closer look and see if I can see any issues.  
Is it possible you can send me you kodi log after you try to open it when the ones that fail to open.
Thanks
