### ISSUE TITLE
Im done!

### ISSUE THREAD

**Issue by Tempest0580** [Tempest0580/tempest#37]
I will no longer be pushing updates of any kind. I'm so tired of spending time making scrapers for my addon for someone else to take it and remove my name off of them and claim they made it. 

Thanks

**Comment by marson53** [comment]
I'm so sad to here this , I know it must be fustrating to have all the hard work you do making new scrapers for your addon , only to find them In others with no acknowledgement for your work , I would like to Thank you, and appreciate all the hard work you have done keeping Tempest updated over the years , I'm going to miss you and your add on As will many other users will too

**Comment by Tempest0580** [comment]
Thanks marson, I really hate to stop and leave people hanging. It's just so frustrating spending time make scrapers and improving scrapers just to see them end up in openscrapers and other addons by people claiming they wrote them. I know I'm not the best coder out here and I'm learning and improving my code daily but people just have no concept of respect anymore. So I'm just going to just keep tempest going to myself. 
Again im sorry to all that use my addon.

**Comment by YKL66** [comment]
First off, Thank you for such awesome add-ons, Tempest and Temptv. I was only using these 2 as dependable never worrying about spam from your work with a clean install kodi was all I needed. Such awesome work to have stolen, not to be given credit is beyond comprehensible. I'm lost for words on how history keep repeating itself in this community. I'm going to miss work 4 sure... Take care and I hope you do come back after you find away to keep your good work from being stolen. One again thank you!

**Comment by Tempest0580** [comment]
Thanks YKL66, I may keep updating temptv. And once I figure out a way to keep all these ungrateful people from stealing my scrapers I'll update tempest. 

I should have left years ago when it all started with I-A-C stealing my scrapers. The part that sucks the most is that if anyone really look more than half of the torrent and dll scrapers in all these addons are mine yet not one of them reflect that. 

That's okay.
Thanks again

**Comment by bjgood** [comment]
First JewBMX, and now you! Man, I wish you'd change your mind. What are we, the end user, going to do? To say I'm going to miss you is an understatement. I've enjoyed your work, dude.

Again, please rethink this decision. A lot of people, like me, depend upon you. I come to your site at least a half dozen times a day. I even go to JewBMX's site every day, even though he has banned me from posting for some unknown reason.

Later, buddy.

**Comment by Tempest0580** [comment]
Thanks bjgood, I'll think on whether I'll push more updates for tempest.  

As of now I plan of keeping temptv going. I've been negotiating the 1 click movies and shows lately.  But I plan on updating those soon with more. And I'm working on a couple more live tv sources so it will give more choices/backups when/if some go down. And going to see if I can improve on the sources that I already have.

**Comment by feenx888** [comment]
Well first time posting. I have to say Tempest have been the best for me for the past year. So much that I want to keep it to myself lol. I hope you will rethink your decision. If I can help in anyway, let me know. I know how it can suck when ypur work is stolen and gets no credit from it.

**Comment by Tempest0580** [comment]
I'm considering it. I'm working on trying to rewrite my scrapers so people cant take them.

**Comment by ts2art** [comment]
You know i am very interested in learning coding and such. I hope you do reconsider! Like i said before Tempest and TempTv have been awesome. Please let me know if there is anything I can do!!

thanks

**Comment by Tempest0580** [comment]
Well I'm going to push a update soon. Not really much for scrapers per say. Mostly some minor code updates for headers. Mainly for ustvgo.

Not sure what I'm going to do as for the scrapers yet.

**Comment by ts2art** [comment]
Not sure what scrapers are... But doing some research to try and get my
feet wet!! Thanks for what you DO!! It is appreciated and Welcomed!!
Unfortunately there is always the bad apples who spoil ut for everyone
else!!

**Comment by Tempest0580** [comment]
Scrapers are used to pull the sources from various websites to play inside kodi. 
And I started by watching some basic videos on python 2 then started breaking down the addon and scrapers and websites to figure out how it all works and went from there. 
I'm far from the best coder but I'm always learning. Learn more everyday.

**Comment by Tempest0580** [comment]
Pushed a update. Some minor scraper updates as well.

**Comment by ts2art** [comment]
Thank you very much!!

**Comment by newf276** [comment]
Heart breaking for sure.  Your work is greatly appreciated by a significant amount of people, and we will truly miss having you provide us all rock solid work, and in my opinion, the best add-on out there.  I can only imagine how frustrating this must be fore you.  I will definitely be very sad to see you leave, but like the rest of the folks understand how you came to this decision.  Thank You, you are very much appreciated by me and many others. :(

**Comment by Tempest0580** [comment]
> Heart breaking for sure. Your work is greatly appreciated by a significant amount of people, and we will truly miss having you provide us all rock solid work, and in my opinion, the best add-on out there. I can only imagine how frustrating this must be fore you. I will definitely be very sad to see you leave, but like the rest of the folks understand how you came to this decision. Thank You, you are very much appreciated by me and many others. :(

Well I'm not sure exactly what I'm going to do yet. I have a few scrapers I've been testing and haven't decided if I'm going to release them yet or not. I did push a update to add headers to most of the scrapers for now. And I'm working on some more live tv. So once I really decide I'll post back here.
