### ISSUE TITLE
Another ustvgo issue

### ISSUE THREAD

**Issue by TGMisfit** [Tempest0580/tempest#39]
First off, I want to say I love this app and especially appreciate it now during this lockdown. I have been experiencing intermittent ustvgo issues for several weeks, but usually could connect after a day or two. It has been down now for three days. I did try clearing the cache and metadata (also have been clearing my Kodi 18.6 cache regularly), uninstalling and reinstalling both Kodi and Temptv to no avail. I will assume traffic is the problem and hope it clears up soon. Thanks again for your wonderful service!

**Comment by Tempest0580** [comment]
Ustvgo has been having issues for a week of so with all the traffic then changed some code on the site this morning.  I'm working on a fix. As soon as I can get it working again I'll push a update. 
Thanks

**Comment by Tempest0580** [comment]
Pushed a update, Its a crude fix for now. May have to click the channels more than once.
Working on a better fix.
Thanks

**Comment by TGMisfit** [comment]
Wasn't working for me at all earlier this afternoon (even clicking a few times), but now it is. Thanks so much!

**Comment by TGMisfit** [comment]
Just wanted to let you know it's NOT working for me again, at least the TCM stream isn't. Guess I'll have to try and watch it online.

**Comment by Tempest0580** [comment]
They have changed they security again.

**Comment by TGMisfit** [comment]
Oh boy, suspected as much. Thanks for the update.

**Comment by Tempest0580** [comment]
You can try arconaitv until I can figure out a fix. They use the same source. But not all the channels work.

**Comment by TGMisfit** [comment]
Will do. Thanks.

**Comment by meNick** [comment]
ustvgo is not working for me on any channel. ditto for temptv as well.
fyi - I am using streamlive which is available in both tempest and temptv and all channels working.

**Comment by Tempest0580** [comment]
Pushed a update hopefully it will stay working for a while. Should come through shortly. 
Thanks

**Comment by meNick** [comment]
Good news! version-5.0.50 (just released) runs all channels in ustvgo and in streamlive. :)
But the new repo 0.0.6 fails to install. That's okay since the current repo 0.0.5 works.
Thank you and a tip of my hat. I'm sure you will fix temptv soon -- these are 2 of my go-to apps hands down.

**Comment by Tempest0580** [comment]
It should be all working soon. I fix it. I was messing around with a new repo and forgot to remove it before I updated

**Comment by Tempest0580** [comment]
I'm working to try and put all 3 of my addons into 1 repo. When I started I didnt fully understand how the repos worked. Lol

**Comment by meNick** [comment]
Thanks again for everything... please consider this: sometimes it's good having choice (tempest/temptv) they really are not the same and I will jump from one to the other when one is not working sometimes the other is. By consolidating it is all or nothing. I know it's extra work supporting two addons but just think how famous you would be :)

**Comment by TGMisfit** [comment]
Still not getting anything on ustvgo, but am confident I soon will be!

**Comment by Tempest0580** [comment]
I meant I was wanting to put all 3 addons into 1 repo. And the only difference between tempest and temptv is that tempest movie and show scrapers. The live tv and 1 clicks are in both. And arconaitv is in all 3.

**Comment by Tempest0580** [comment]
> Still not getting anything on ustvgo, but am confident I soon will be!

It should update soon.

**Comment by meNick** [comment]
@TGMisfit - you should have it by now. version-5.0.50 works. I'm using it for CNN & Foxnews.
@Tempest0580 - whatever you decide on app consolidation I know is going to be great.

BTW, I've been on github for years and this is the first time my leaving messages. Just wanted to say thanks for your work and for sharing. Stay safe.

**Comment by TGMisfit** [comment]
Mine is still not working (and I have that version installed). I cleared Kodi and Tempest caches (as well as metadata for Tempest). Not uninstalling and reinstalling again. I've already done that several times to no avail.

**Comment by meNick** [comment]
I'm just a user so what I say may just sound stupid but since I know version-5.0.50 absolutely works can you just double-check your version number? I know you said you did that. Assuming the version checks then select ustvgo, then try CNN and try FoxNews. Are you saying that these will not display video at all? Is that what you are saying? Or something else.

An answer to this might help in getting closer to the problem. Anything more than "not working" would be helpful.  "not working" how? Something that might be repeatable. I will try as much as I can to help bearing in mind that I am just a user.

**Comment by Tempest0580** [comment]
Can you post you log?

**Comment by TGMisfit** [comment]
I'm going to clear providers and see what happens. I think I only cleared the cache and the metadata before.

**Comment by meNick** [comment]
@TGMisfit - I don't want to keep you hanging... I tried fiddling with different config settings but could not get ustvgo to not display any video. That's all I do. As I said I'm just a user. But I see that @Tempest0580 is asking for a log file. If anyone can fix it for you it's him. Hope it works for you. I think this is one of the best addons for Kodi.

**Comment by TGMisfit** [comment]
Thanks so much, Nick! I have been able to get a few streams working, but others still don't. I have been checking the log for any changes. I guess it will have to suffice for now. Thanks again. I really appreciate your help.

**Comment by meNick** [comment]
Well, as of right now both Tempest and TempTv are down on channels (ustvgo & streamLive,  FoxNew,) very unstable.

Just saying (not complaining). Just FYI.

**Comment by meNick** [comment]
Please don't think I've escaped from the coo-coo bin. All I'm trying to do is give you some real-time experience... -- so now it is 7:20om Central time and both Tempest and TempTv have been running ustvgo and streamlive,  FoxNews continuously for about 45 minutes.

So, the earlier hiccups could have been that the channels themselves were being hit with a lot of traffic,. If true then nothing wrong with the apps. I will not yell "the sky is falling" (I promise) and just wait. I'm sure the Dev can use the time much better than dropping everything on what bee really nothing.

Thanks for bearing with me.
