### ISSUE TITLE
Series9

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/tempest#40]
Hey Tempest,
I was wondering, when you get the time, if you can take a look at series9.py? It's using cloudflare now, as you probably know. Normally, series9 and seriesonline (which is working) are pretty much the same, so, no hurry on my request.

And, swatchseries is down, too. Maybe shellc0de27 will read this and take a look.

Thank you.

Later...

**Comment by bjgood** [comment]
I found one that works over at openscrapers.

**Comment by Tempest0580** [comment]
Sorry man my computer messed up, once I fix it I'm going to work on updating adding some scrapers.

**Comment by bjgood** [comment]
There's a bunch over at openscrapers. Why not "borrow" some of theirs? Venom submitted them. Most are updated versions of yours and JewBMX's, and he left the authors name on each. Good dude.

Later, Tempest.
