### ISSUE TITLE
Movies>in theatres error

### ISSUE THREAD

**Issue by WookieJuice** [Tempest0580/tempest#43]
Hi, superb addon. However, I’ve noticed the ‘in theatres’ link in Movies section directs you to Live IPTV>Movies list and not an IMDB list of movies. Hope this makes sense. Regards

**Comment by Tempest0580** [comment]
I'll check in it. 
Thanks

**Comment by Tempest0580** [comment]
So i looked into this, With all this lock down going on the "In Theaters" can't pull any info from imdb.
On the website it says "While theaters are closed, some data on this page may be delayed or unavailable", It is setup to try and pull info for your area or close to it.
The old style is still working so i would suggest using it until the Theaters open back up.
Thanks
