### ISSUE TITLE
More rlsbb issues

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#44]
Think rlsbb scraping is failing again but also in last couple of update oncedll and scenerls results have disappeared.

**Comment by Tempest0580** [comment]
If I'm correct I think scenerls is not behind captcha now. 

And if your using the debrid check then rlsbb is taking to long to return links. Next update I'm going to remove it unless I can find a better way to code it to be able to return links with the debrid check on. 
Thanks

**Comment by Pawman63** [comment]
The rlsbb app also fails now so I think it's the cloud flare crap it's a pity as they have the most links.

**Comment by marson53** [comment]
Rlsbb add on is working again , There was a cloud flare cfscrape update yesterday , also Rlsbb links work OK now on adding that have updated cfscrape

**Comment by Tempest0580** [comment]
Rlsbb and oncedll should now be working in the new update.
Thanks
