### ISSUE TITLE
Other & Cosmetic issue

### ISSUE THREAD

**Issue by techecoyote** [Tempest0580/tempest#46]
First, thank you for all the great work, much appreciated.

I've noticed when using Tempest or Temptv, Arconai 24/7, Cable section. Once you click on a network it plays fine. Then you back out & try another network, or even exit addon all together that the previous networks listed (you already played) disappear completely from the list.
Maybe is just me... but thought I would mention it.

Cosmetic issue, I feel really stupid for even saying this but the Arconai sections is each addon is spelled Acronai from the navigator menus. It really should be a r c o n a i.

I apologize in advance for even mentioning it but again thought to let you know.

**Comment by Tempest0580** [comment]
Go left on the screen and make sure the filter is set to all videos and to not filter out the ones already play. Once you watch something it marks it as played so your setting may be removing those from the list.

And I never noticed the spelling was wrong lol I'll fix that typo.
Thanks

**Comment by Tempest0580** [comment]
Spelling Typo fixed in new update.
Thanks

**Comment by techecoyote** [comment]
Thx for the update. Sorry about about being so picky.

Forgot to mention the Radio section in TempTv gives an error. Tempest Radio works fine.

2020-05-01 15:15:26.176 T:17028   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named sources
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi18\portable_data\addons\plugin.video.temptv\temptv.py", line 330, in <module>
                                                from resources.lib.indexers import radio
                                              File "C:\Program Files\Kodi18\portable_data\addons\plugin.video.temptv\resources\lib\indexers\radio.py", line 7, in <module>
                                                from resources.lib.sources import cfscrape
                                            ImportError: No module named sources
                                            -->End of Python script error report<--
2020-05-01 15:15:26.309 T:12788   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.temptv/?action=radioNavigator
2020-05-01 15:15:26.327 T:15408   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.temptv/?action=radioNavigator) failed

Thx again for the most excellent work & time...

**Comment by Tempest0580** [comment]
No problem I'm glad you caught the typo. And I'll take a look at the radio in temptv, I code everything in Tempest then add it to temptv and with the code being different in the two sometimes it causing issues and sometimes forget to test it in both lol
Thanks

**Comment by Tempest0580** [comment]
Update should come through soon with the radio section fixed. Thanks for letting me know.

**Comment by techecoyote** [comment]
No problem. Glad to help. I know it takes time & gets confusing when your juggling different addons / code & builds. I do the same thing with my stuff. I do addons/forks/builds for my friends & family. Started almost 4 years ago. Got tired of the public addons coming out not working or giving errors. So then started fixing them. Then I decided to teach myself all this crap & just try to rely on myself. No I don't consider myself a developer because I don't know python. Just work everything backwards and make it work. So again, thanks for the time. Maybe we could talk on telegram some time....

**Comment by Tempest0580** [comment]
That's how I got started myself.  After the original dev of exodus quit and it just kept getting screwed up after that I started doing it for myself.  I still have alot to learn and learn more everyday. 
Honestly the best way for me to talk off of here is through emails.

**Comment by techecoyote** [comment]
Gotcha, lol.Small world. Ok, well I wanted to ask you about scrapers. I'm too cheap to pay for RD. So I'm trying to figure out the whole scraper thing. Making them & putting them together. I liked Tiki when he did his, you could use his or anyone elses out there. The best of every world. But since he stopped it, IK wanted to do something like that as well. For myself & if its good enough, for the public. Love openscrapers but I want more options... Everyone seems to be just pushing the RD thing & passing on free scrapers. Love Jewbmx as well. Don't know if thats an alias for you or someone else. But he did great work on scrapers from what I have seen. I would like to find a mentor / help for the scraper project or other addons(forks) as well. It's hell trying to do this all by yourself, but it's fun for me. Anyways, sorry about the preaching, just looking to talk with someone else & vent about this stuff.
Thx again for the listening ear. Appreciate it. Hit me up sometime somewhere...

**Comment by Tempest0580** [comment]
I've done alot of work with Jewbmx, he is a pretty good dev. I'm not a fan of openscrapers they take other people's scrapers and claim them as their own. Alot of mine for example.
If your wanting to learn how to make scrapers I highly recommend learning the basics of python, then work through scrapers that work to see how they work. 
Then trying coding your own. That's how I got started.
