### ISSUE TITLE
Rlsbb again

### ISSUE THREAD

**Issue by Pawman63** [Tempest0580/tempest#48]
Don't know if this is an ongoing issue with rlsbb.to but it is a regular issue that links on there won't scrape. Cloudflare again I take it.

**Comment by Tempest0580** [comment]
I'll check into it. 
Thanks

**Comment by CatsRidingRoombas** [comment]
Just want to thank you for trying to keep all this stuff working, not an easy task under these conditions.
________________________________

**Comment by Tempest0580** [comment]
Sorry been very busy. I updated cfscrape so this should be working again.
Thanks

**Comment by Pawman63** [comment]
Great work

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
