### ISSUE TITLE
Movies/People Watching/ ... Results are not movies but TV Networks

### ISSUE THREAD

**Issue by durangorob** [Tempest0580/tempest#49]
In the tab of Movies/People Watching in this last update the contents are not coming up with titles of Movies.  Instead it is populated with a list from the TV Networks like HBO, Starz, Showtime, Movie Kingdom, Pluto.  Please check it out and correct it so it actually shows the Movies that People are Watching.

Thank you guys for all your hard work for this terrific addon.

Bob W.

**Comment by Tempest0580** [comment]
Thats a bug i have not been able to work out but that normally happens when its not able to connect to the site its trying to pull the info from. It works fine on my end. Still having the issue?
Thanks

**Comment by durangorob** [comment]
Not now.  It seems to have cleared up.  Thanks for the reply and all your work.
Bob W.
    On Wednesday, May 6, 2020, 06:28:50 PM CDT, Tempest <notifications@github.com> wrote:  
 
 


Thats a bug i have not been able to work out but that normally happens when its not able to connect to the site its trying to pull the info from. It works fine on my end. Still having the issue?
Thanks

**Comment by Tempest0580** [comment]
Ya it may have just been having issues polly the info the the site. But I'm glad it's working again.
