### ISSUE TITLE
Youtube Trailers error

### ISSUE THREAD

**Issue by rjbweb** [Tempest0580/tempest#50]
I have included my API into youtube and trailers still dont work.
havent managed to see trailers for a long long time...

**Comment by Tempest0580** [comment]
Sorry been very busy. I'll look into this but I'm also going to see if I can add some more api keys in so the trailers will work longer before the api limit is reached.
Thanks

**Comment by meNick** [comment]
Trailers not working on version 5.0.77

**Comment by rjbweb** [comment]
Still no trailers
