### ISSUE TITLE
Vpn issues.....

### ISSUE THREAD

**Issue by ts2art** [Tempest0580/tempest#54]
Morning, Im not sure who can help with this issue. I have NORDVPN installed on my firestick. Lately if I try to update addons or try to watch PlutoTv or The Adult section (With Nord on it acts like its going to work then NOTHING!! I needed to update an Addon... when i clicked update... it said update failed. So I turned off Nord and went back in and it updated and also let me access PlutoTv!! Any suggestions???

Thank you
Troy

**Comment by Tempest0580** [comment]
Honestly not sure I can help without doing some research.  I dont use a VPN myself.

**Comment by ts2art** [comment]
Thank you anyway! Appreciate all your hard work!

**Comment by bjgood** [comment]
I use Nord and have no trouble at all. The only difference is that I use a raspberry pi instead of a firestick to run tempest.
