### ISSUE TITLE
Yes network 

### ISSUE THREAD

**Issue by bugsy55** [Tempest0580/tempest#55]
Yes network does not work under USA Tv Go... That’s the only place I find the yes network!
Any ideas why?

**Comment by Tempest0580** [comment]
Pushed a update that should fix this, UstvGo changed code on the site.
Thanks

**Comment by bugsy55** [comment]
Now this will fix Tempest and Tenp tv?

**Comment by Tempest0580** [comment]
Yes I pushed a update for both. Not sure if or when the website will change again though.
