### ISSUE TITLE
Wrong update?

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/tempest#58]
Hey Tempest,
Did you post the wrong update (4.0.87) for tempest today? I looked it over and everything inside it is old. There's no ustvgo.py in the indexers folder, and cfscrape, in the modules folder, is real old, too. 
Just curious.

Have a good one, bud.
Later...

**Comment by bjgood** [comment]
This was on purpose, wasn't it? It should have been 5.0.70, or something close to it.

It was either on purpose, or someone has hijacked your github.

Hope everything is alright with you, dude. I'm a little worried.

Later...

**Comment by edb64** [comment]
I'm also concerned that it's been jacked because now it's installing URL Resolver and no premium sources/torrents are coming back from scrape 🤔

**Comment by Tempest0580** [comment]
No it was a accident on my part. My repo got wipe in a update I pushed 2 weeks ago. And the update I pushed night before last to fix it was the wrong one. I should have it fixed tonight. Sorry about that. Thanks

**Comment by edb64** [comment]
Phew, thanks for the update 👍

**Comment by Tempest0580** [comment]
Repo has been fixed. Thanks

**Comment by edb64** [comment]
Thank you 👍

**Comment by edb64** [comment]
Just noticed a glitch in how results from SOLID TORRENTS source are showing up for file size;
1 | 3 |. |7 | 4 | G | B
Every else is looking good and sources are working great 👍
