### ISSUE TITLE
MkvCage torrent scraper broken

### ISSUE THREAD

**Issue by Tinuz97** [Tempest0580/tempest#6]
MkvCage torrent scraper broken. just fyi.

**Comment by Tempest0580** [comment]
Ok thanks. I'll take a look at it and see about fixing it.

**Comment by Tinuz97** [comment]
thx

**Comment by Tempest0580** [comment]
Mkvcage scraper has been fixed.

**Comment by Tinuz97** [comment]
Confirmed, working great again, thx.
Installed zip from git (not in repo yet I guess) 👍

**Comment by Tempest0580** [comment]
Your welcome.
