### ISSUE TITLE
Updated Scrapers

### ISSUE THREAD

**Issue by marson53** [Tempest0580/tempest#60]
Thank you for the update for the scrapers , some fixed and a new torrent one 

I have managed to get the  YIFYDDL torrent scraper Working again you just need to change the site address from yts.ws to yifyddl.co 
Thanks...

**Comment by bjgood** [comment]
I check the site address of a given scraper all the time.  You'd be surprised how often that works.
Congratulations on your diligence.

**Comment by Tempest0580** [comment]
> Thank you for the update for the scrapers , some fixed and a new torrent one
> 
> I have managed to get the YIFYDDL torrent scraper Working again you just need to change the site address from yts.ws to yifyddl.co
> Thanks...

I'm going to try to get more scrapers fixed/updated in the next update. hopefully ill be adding some as well. Thanks

**Comment by marson53** [comment]
Thanks look forward to the update , just to let you know the your ONCEDDL scraper has stopped working because they have changed Web address I have changed it to the new one and it works OK , change to 2ddl.ms

**Comment by Tempest0580** [comment]
> Thanks look forward to the update , just to let you know the your ONCEDDL scraper has stopped working because they have changed Web address I have changed it to the new one and it works OK , change to 2ddl.ms

ONCEDDL must have just changed it cause I just update the scraper. Lol
