### ISSUE TITLE
HEVCBAY Scraper 

### ISSUE THREAD

**Issue by marson53** [Tempest0580/tempest#61]
Hi , I've found a bizarre error could you check this for me , If I goto movies year 2019 and then click Knives Out or Joker movie the search locks up I then have to restart kodi , but if I disable HEVCBAY Scraper and  try again, it pulls the link for the movie OK  Thanks

**Comment by Tempest0580** [comment]
> Hi , I've found a bizarre error could you check this for me , If I goto movies year 2019 and then click Knives Out or Joker movie the search locks up I then have to restart kodi , but if I disable HEVCBAY Scraper and try again, it pulls the link for the movie OK Thanks

Thanks ill check into this.
