### ISSUE TITLE
RLSBB Scraper fix

### ISSUE THREAD

**Issue by marson53** [Tempest0580/tempest#64]
RLSBB Scaper has stopped working , to fix it you have to change the scraper address where it says rlsbb.ru and change all to rlsbb.to

**Comment by Tempest0580** [comment]
Thanks ill update this and push out a update soon.

**Comment by bjgood** [comment]
Hey Tempest,
Thanks for all the source updates, bud! Quite a number of them. Much appreciated.

**Comment by Tempest0580** [comment]
> Hey Tempest,
> Thanks for all the source updates, bud! Quite a number of them. Much appreciated.

Your welcome. Hope to have more coming soon.

**Comment by bjgood** [comment]
Tempest,
If you get a chance check out 5movies. It stopped working here very recently...at least on my end.
Also, watchseries has stopped working as well.
Later, bud.
