### ISSUE TITLE
Swatchseries.to is gone

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/tempest#65]
Hi Tempest,
As you may have noticed already, swatchseries.to is down. And, from what I've learned, it's gone for good. It has been taken down, along with a bunch of other sites, by the DMCA originating in Australia.
It has been a great site for a long time. It was one of the best if not the best for TV shows.
Thought I'd pass it along.

Later...

**Comment by Tempest0580** [comment]
Thanks, Im working on some more scrapers. Hopefully ill have them ready soon

**Comment by bjgood** [comment]
Thanks for the reply, Tempest.
Have a good one, bud.

Later...

**Comment by Tempest0580** [comment]
> Guess I spoke too soon. Ha!
> It's changed its address to https://www1.watch-series.la, but it doesn't work when substituted in the python file. The search function box on the web site does not work (like one time before).
> Have a good one, bud.
> 
> Later...

This will be fixed in the next update,  along with 1 or two others. Thanks

**Comment by bjgood** [comment]
Thanks, Tempest, for the new and updated scrapers. They work pretty well. :).

Happy holidays to you and yours, Tempest. And, that goes to everyone else, too. Even JewBMX...;).

Later...

**Comment by Tempest0580** [comment]
swatchseries.to is now update in the new update along with a couple other scrapers. Thanks and happy holidays
