### ISSUE TITLE
Pirate bay Scraper

### ISSUE THREAD

**Issue by marson53** [Tempest0580/tempest#67]
I Just wanted to know if your piratebay scraper is working for you with Tempest, I have to use a proxy being in the UK and changed when needed but I have not been able to find a working one for some time. So not sure if there are any problems with the piratebay scraper. Thanks

**Comment by Tempest0580** [comment]
> I Just wanted to know if your piratebay scraper is working for you with Tempest, I have to use a proxy being in the UK and changed when needed but I have not been able to find a working one for some time. So not sure if there are any problems with the piratebay scraper. Thanks

Piratebay scraper is working fine on my end.
