### ISSUE TITLE
Search and scrappers

### ISSUE THREAD

**Issue by jpstar12** [Tempest0580/tempest#68]
Thanks for keeping current the best most stable Add On available! 

Out of nowhere, the TV show search function has stopped working. A show I’ve been watching for some time now so know it has sources, started showing no results as if it’s not really searching. I’ve tried other searches and soon as the spinning wheel pops up as it’s searching,
It’ll disappear almost instantly as if no show exists. I resprung and reloaded kodi. 

If it may be of use, Exodus search is doing the same thing. Other Add ones are not.

**Comment by rustyshax** [comment]
I am wondering if the app is down? I cannot seem to install it right now

**Comment by jpstar12** [comment]
Though it seems as the amount of sources is lower, the search function seems to be searching again. The issue I’ve stated above seems to not be an issue any longer. 

Thank you guys just the same! Great add on
