### ISSUE TITLE
Dependency not met

### ISSUE THREAD

**Issue by rustyshax** [Tempest0580/tempest#69]
I keep getting this message when installing:

"The dependency on script.module.six version 0.0.0 could not be satisfied"

Any ideas on what to do?

Thanks in advance.

**Comment by Tempest0580** [comment]
> I keep getting this message when installing:
> 
> "The dependency on script.module.six version 0.0.0 could not be satisfied"
> 
> Any ideas on what to do?
> 
> Thanks in advance.

Are you still having a issue with this?

**Comment by rustyshax** [comment]
I tried several times yesterday, even deleted kodi and did full reinstall and still nothing. So weird!

**Comment by Tempest0580** [comment]
That is weird, I heard a lot of people was having issues with addons not installing or working correctly.  Have you tried it today?

**Comment by rustyshax** [comment]
I did not have a chance to yet, however I will def check it out and try
again tomorrow
