### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by cprime1213** [Tempest0580/tempest#7]
Hi when I click on any of the selections like movies even search it loads to a page with no movies on it just the three dots to take you back if you can help it would be much appreciated thanks.

**Comment by Tempest0580** [comment]
Can I get a little more information? 
What kodi version are you running? 
What version of Tempest are you running?
Did you try clearing metadata and cache? 
Thanks

**Comment by Tempest0580** [comment]
Closing this, Going to assume this issue was figured out.
