### ISSUE TITLE
VPN locked or the code has changed

### ISSUE THREAD

**Issue by isacodehub** [Tempest0580/tempest#70]
Getting this error on KODI ipvanish

**Comment by Tempest0580** [comment]
That's for UstvGo and they require nordvpn and as far as i know that's the only one that will work. Nothing i can do about it. Thanks

**Comment by t3chguru36** [comment]
Im receiving the same error code even on the free channels that doesnt require a VPN

**Comment by isacodehub** [comment]
I did a fresh install of my build and it’s fine now.

**Comment by t3chguru36** [comment]
There were available addon updates so I updated and now its working for me 😀

**Comment by t3chguru36** [comment]
I can get around there nordvpn requirements on a pc and watch all of the channels for free but Id like to watch through kodi 😀
