### ISSUE TITLE
Tempest live TV 

### ISSUE THREAD

**Issue by imatini** [Tempest0580/tempest#72]
Hello

I experience a problem with live TV on tempest when I try to log in to USATVGO it seems that the VPN on all channels is locked or code has changed it shows me always that exact message although my friend has no problem with this on his android tv

**Comment by Tempest0580** [comment]
> Hello
> 
> I experience a problem with live TV on tempest when I try to log in to USATVGO it seems that the VPN on all channels is locked or code has changed it shows me always that exact message although my friend has no problem with this on his android tv

Please check out the Live TV issues below. Thanks
