### ISSUE TITLE
Usatvgo says VPN locked or code has changed

### ISSUE THREAD

**Issue by teecres** [Tempest0580/tempest#75]

**Comment by teecres** [comment]
I'm using version 2.0.82 on fire-stick. Uninstalled & reinstalled, still locked

**Comment by Tempest0580** [comment]
> I'm using version 2.0.82 on fire-stick. Uninstalled & reinstalled, still locked

Please check out the Live TV issues below. Thanks

**Comment by marion90212** [comment]
It's still locked or code has changed

**Comment by bjgood** [comment]
ustvgo has changed back to base64 (as I'm sure Tempest already knows).

Hey Tempest.

Later...

**Comment by Tempest0580** [comment]
Pushed a update to fix UstvGo, Code Changed. Thanks
Some Channels are VPN Locked
