### ISSUE TITLE
Kindly Check this site

### ISSUE THREAD

**Issue by Deb3709** [Tempest0580/tempest#79]
This site have more than 100k Movies.Is it possible to add streamtape,mystream and doodstream from this site.

https://zmovies.123movies.online/

**Comment by Tempest0580** [comment]
> This site have more than 100k Movies.Is it possible to add streamtape,mystream and doodstream from this site.
> 
> https://zmovies.123movies.online/

Next update with fix move2k scraper which is the same site as the one you posted but as far as I can tell has more movies and tvshows. Thanks

**Comment by Deb3709** [comment]
What's the full domain of move2k website? Thanks a lot.

**Comment by Tempest0580** [comment]
> What's the full domain of move2k website? Thanks a lot.

https://movie2k.123movies.online
Your welcome
