### ISSUE TITLE
Trakt progress not working on new update 

### ISSUE THREAD

**Issue by DoBucki** [Tempest0580/tempest#8]
Rolled back to old version and got it working

**Comment by Tempest0580** [comment]
Ok thanks I'll look into it.

**Comment by Sarafian** [comment]
I confirm. From the looks of it functionality related to episodes with trakttv is broken. History, progress and episodes list are broken. When I go through the list to a show then the show won't open.

It seems to me that at the moment a show or an action needs to resolve into episodes then it breaks. 

I tried the same function from other obsolete add-ons and it works, so I don't believe that the API changed.

I hope the feedback helps you narrow down the problem faster.

**Comment by Tempest0580** [comment]
This should be fixed in the update I pushed. Please let me know. Thanks

**Comment by DoBucki** [comment]
All good looks like it's working. Appreciate all that you do love your addon. you're one of the very few that actually respond

**Comment by Tempest0580** [comment]
Your welcome.  I do my best to keep it working for everyone.
