### ISSUE TITLE
repository issues

### ISSUE THREAD

**Issue by oslender** [Tempest0580/tempest#82]
Hi,
I am try to install the tempest addon on my new android tv box.
when I get inside the repository , I do the installation of the addon and get note of : ' the dependency on script.module.idna version 2.6 code'.
I change the version of the Kodi 18.2  18.6  18.9  and 19 and it didnt work on any of theme.
I using the addon on other sources and its working great...
I hope you will be able to help me to install it to my new box

Oren

**Comment by marson53** [comment]
It seems idna module is missing from official kodi repository, The only way I can think off to fix this for now ,is to install ReleaseHub addon by Bugatsinho , he has added the idna module to his repo and will install the missing inda allowing you then to install Tempest, I'm sure Tempest will fix this in his repo when he gets time . Hope the works for you

**Comment by Tempest0580** [comment]
> Hi,
> I am try to install the tempest addon on my new android tv box.
> when I get inside the repository , I do the installation of the addon and get note of : ' the dependency on script.module.idna version 2.6 code'.
> I change the version of the Kodi 18.2 18.6 18.9 and 19 and it didnt work on any of theme.
> I using the addon on other sources and its working great...
> I hope you will be able to help me to install it to my new box
> 
> Oren

I'll look into fixing this.

**Comment by oslender** [comment]
its working great now, thank you very much that you took care of it...
