### ISSUE TITLE
Update 4.0.71

### ISSUE THREAD

**Issue by brianlee1961** [Tempest0580/tempest#9]
Since last update Tempest scrapes for links  shows links are scraped but no links show up

**Comment by Tempest0580** [comment]
I'll look into it. Thanks

**Comment by Tempest0580** [comment]
Just pushed a Update, Clear cache and providers and see if that fixes your issue, Thanks

**Comment by MarcusPiippo** [comment]
This does not work, i did this and still it finds all the links, but soon as the scraping is done. I just get a blank list with 3 dots to go back again. Frustrating  hope it get fixed when Tempest is the best addon in Kodi

**Comment by DoBucki** [comment]
I can confirm, pulls links but shows none to play,  I just rolled back to previous version and is working

**Comment by Tempest0580** [comment]
I'll take another look at it. Seems to be working fine for me but I'll do some more testing.

**Comment by MarcusPiippo** [comment]
@DoBucki Any way to do a roll back on Apple TV ? I I tried Yoda but, Tempest is still the best one by far

**Comment by Tempest0580** [comment]
I'm going to push 4.0.70 until I can figure out the issue.

**Comment by Tempest0580** [comment]
Pushed a update back to 4.0.70 code, Give it a few minutes and update it.

**Comment by MarcusPiippo** [comment]
What a guy! That worked wonders, thanks for being so responsive and thanks for giving us this awesome app!

**Comment by brianlee1961** [comment]
Cheers 4.0.73 update all working again

**Comment by Tempest0580** [comment]
Your welcome Marcus. I'll keep it updated as much as I can. I'm working on a live TV addon now so it's taking some of my time.

**Comment by brianlee1961** [comment]
Is your repo down or have you changed your url tried to do a fresh install would not connect in file manager

**Comment by Tempest0580** [comment]
New repo https://tempest0580.github.io/

**Comment by brianlee1961** [comment]
Many thanks

**Comment by brianlee1961** [comment]
Many thanks this is my go to addon for reliable streams

**Comment by brianlee1961** [comment]
Tempest does not seem to pull in free streams for some of the the shows I
watch although I have real debrid no links generated for certain shows I
watch e.g. NYPD BLUE are you not maintaining free providers anymore
Many thanks for the hard work
